title: Audrey Nosenga # your name (or website title) here
logo: "images/DSC07243_Original.jpg" #your photo (or logo) here
Professional Summary: > # your text below (remove <br> elements if you don't need line breaks)
 An accomplished dual professional with skills in data science and healthcare, with a growth mindset and passion for utilizing technology. I enjoy teamwork, tackling challenges, finding solutions, adding value, and I take ownership and responsibility for products. Looking for a position as a data analyst in a fast-paced company. 
  <br><br>
  <h5>Contact Me on:</h5>
  <br><br>
  <a href="https://www.linkedin.com/in/audrey-nosenga/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/audrey1993">View My GitHub Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
